### ISSUE TITLE
Windows 10 export issue

### ISSUE THREAD

**Issue by davord45** [funexpected/flash-tools#1]
Hello
I get the following error when i try to use Export.jsfl in Adobe Animate 2020 on Windows 10
![image](https://user-images.githubusercontent.com/70846358/109356307-d0410080-7880-11eb-97ea-453b36350a56.png)
I followed the instructions in README.

**Comment by davord45** [comment]
It only manages to make a recover fla project

**Comment by jkb0o** [comment]
Looks like there are wrong path delimiters. Will fix it shortly.

**Comment by jkb0o** [comment]
@davord45 can you please copy-paste all output here.

**Comment by jkb0o** [comment]
Should be fixed in `0.2.5` release. Reopen please if not.

**Comment by davord45** [comment]
Can you update the zip linked in the README?

**Comment by jkb0o** [comment]
Readme links to the [latest release](https://github.com/funexpected/flash-tools/releases/tag/v0.2.6), if it doesn't work, then the bug has not fixed probably. Can you please post the output of the export command and error after updating to the latest release?

**Comment by davord45** [comment]
I will test it out once i am back at the laptop

**Comment by davord45** [comment]
I still get these 2 errors. Output is also visible in the screenshots
![image](https://user-images.githubusercontent.com/70846358/109404280-dc05f300-7964-11eb-815c-f214c0b1ca0f.png)
![image](https://user-images.githubusercontent.com/70846358/109404285-e2946a80-7964-11eb-8bb8-1c069b4fcce4.png)
These are the settings that i put in the scripts:
![image](https://user-images.githubusercontent.com/70846358/109404276-d3adb800-7964-11eb-9932-ee5d5aab005e.png)
Tell me if i am not doing something right

**Comment by jkb0o** [comment]
You did everything fine. I've finally got windows virtual machine, fixed and tested all this stuff. Should work like a charm (except I can't run Godot on the virtual machine for now). 

Please, download the latest release (https://github.com/funexpected/flash-tools/releases/tag/v0.2.7) and tell me if there any problems left.

**Comment by davord45** [comment]
It works great,thank for taking the time to fix it
![image](https://user-images.githubusercontent.com/70846358/109431303-24c1b880-7a06-11eb-92a8-fc6221ddcec5.png)

Can i ask you what is active timeline property for? Can it be used to link the animation to AnimationPlayer?

Can you export more than one animation from Adobe animate? Does one zfl contain one animation?

If you could make a tutorial how this module works i would appreciate it!

**Comment by jkb0o** [comment]
You're welcome!

For now, you can export flash in 3 modes: `Document` (only document and dependencies), `Library` (root library items with dependencies), and `Active screen` (only currently edited active item with dependencies). Active timeline property switches what animation (library item) should be played, it is most useful if you export flash in `Library` mode.

For example, there is how one of our library is organized (the document is empty):
<img width="303" alt="Screenshot 2021-02-28 at 23 51 59" src="https://user-images.githubusercontent.com/122736/109433154-f4871380-7a1f-11eb-980d-66b5b2b15ee8.png">

And there is how it appears in Godot:
<img width="240" alt="Screenshot 2021-02-28 at 23 51 30" src="https://user-images.githubusercontent.com/122736/109433142-e5a06100-7a1f-11eb-9f4b-f221e690411e.png">

There are labels and skins (variants) that also may be appeared in the properties, but I'll cover those features in docs and tutorials.

**Comment by davord45** [comment]
This is really amazing,i will definitely keep an eye on new updates!
